### ISSUE TITLE
Avif quality setting doesn't seem to work

### ISSUE THREAD

**Issue by AncientMystic** [gen2brain/cbconvert#31] opened 2024-06-18 22:14 UTC
It seems no matter the settings, avif always produces the same file size, 0-100 quality results are the same.  

Is there something i am missing on my system? 

Also just have to say, thank you for supporting avif, it is so helpful for compressing extremely large documents and adobe doesn't seem to want to support anything higher than jpg/jpg2000 within pdfs, so this is a life saver.

**Comment by gen2brain** [comment] 2024-06-20 06:15
This seems to be a duplicate of https://github.com/gen2brain/cbconvert/issues/20. I have a plan to remove the ImageMagick requirement and to use libraries like https://github.com/gen2brain/avif and https://github.com/gen2brain/webp, but that will probably not happen during the summer.

**Comment by gen2brain** [comment] 2024-11-03 19:17
This is fixed. There is no more ImageMagic.

**Closed by gen2brain** 2024-11-03 19:17 UTC
