### ISSUE TITLE
feature request: tolerate junk _MACOSX and .DS_Store sub-directories in zip archives.

### ISSUE THREAD

**Issue by rwperrott** [gen2brain/cbconvert#37] opened 2024-07-19 15:01 UTC
A sane approach would be to exclude processing or copying of _MACOSX and .DS_Store sub-directories.
It's annoying having to separately manually delete this junk, so that this tool can process these archives.

**Comment by gen2brain** [comment] 2024-07-22 09:43
There is already option `--no-nonimage` or `Remove Non-Image Files from the Archive`, but it probably needs some review.

**Comment by rwperrott** [comment] 2024-07-22 09:52
The snag is that I want to retain any other non image files, like comic meta data files, whereas those Apple MacOS directories are always junk, in my opinion. Fortunately I only see them rarely.

**Comment by gen2brain** [comment] 2024-11-04 16:36
Sorry, if you can just reiterate, the issue is with the existing archives and junk in them, or is the issue when creating new archives (I don't think so, but let's check)? I guess the proposal is to just nuke and ignore whenever.

**Comment by gen2brain** [comment] 2024-11-06 21:44
Addressed in https://github.com/gen2brain/cbconvert/commit/f85fe990ff57b7061c3f513af72862c4448a91b9. Now it will always just skip such files. The new release has been uploaded.

**Closed by gen2brain** 2024-11-06 21:44 UTC
